#!/usr/bin/env bash

DEBUG_MODE=false

portable_nproc() {
    OS=$(uname -s)
    if [ "$OS" = "Linux" ]; then
        NPROCS=$(nproc --all)
    elif [ "$OS" = "Darwin" ] || \
            [ "$(echo "$OS" | grep -q BSD)" = "BSD" ]; then
        NPROCS=$(sysctl -n hw.ncpu)
    else
        NPROCS=$(getconf _NPROCESSORS_ONLN)  # glibc/coreutils fallback
    fi
    echo "$NPROCS"
}

while getopts ":d" OPTION; do
    case $OPTION in
        d) DEBUG_MODE=true ;;
        \?) echo "Invalid option: -$OPTARG"; exit 1 ;;
    esac
done

JUICE_UTIL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JUICE_REPO_DIR="$(dirname "${JUICE_UTIL_DIR}")"
JUICE_BUILD_DIR="${JUICE_REPO_DIR}/build"
JUICE_CMAKE_DIR="${JUICE_BUILD_DIR}/cmake"
JUICE_BIN_DIR="${JUICE_BUILD_DIR}/bin"

rm -rf ${JUICE_BUILD_DIR} || true
mkdir ${JUICE_BUILD_DIR}
mkdir ${JUICE_CMAKE_DIR}
mkdir ${JUICE_BIN_DIR}

cd ${JUICE_CMAKE_DIR}

if [ "$DEBUG_MODE" = true ]; then
    cmake ${JUICE_REPO_DIR} -DCMAKE_INSTALL_PREFIX=${JUICE_BUILD_DIR} -DCMAKE_BUILD_TYPE=Debug
else
    cmake ${JUICE_REPO_DIR} -DCMAKE_INSTALL_PREFIX=${JUICE_BUILD_DIR} -DCMAKE_BUILD_TYPE=Release
fi

make -j"$(portable_nproc)" && make install
